version: '3.1'

services:
  weby:
    build:
      context: .
      dockerfile: Dockerfile
    image: weby
    container_name: weby_ufg
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - webydb
    volumes:
      - ".:/app"
      - gem_cache:/usr/local/bundle/gems
    environment:
      PG_DB: ${POSTGRES_DB}
      PG_USER: ${POSTGRES_USER}
      PG_PASS: ${POSTGRES_PASSWORD}
      PG_HOST: webydb
      SECRET_KEY_BASE: ${SECRET_KEY_BASE} 
      RAILS_ENV: ${RAILS_ENV}
    env_file:
      - .env

  webydb:
    image: postgres:12.1
    container_name: webydb
    restart: always
    expose:
      - 5432
    volumes:
      - "data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
volumes:
  gem_cache:
  data: